# ==============================================================================
# Wallpaper
# ==============================================================================

output * bg ~/.config/wallpaper/flcl.png fill

