# ==============================================================================
# Status Bar:
# ==============================================================================

# Read `man 5 sway-bar` for more information about this section.
bar {
    position top

    status_command while date +"%a %d %b %I:%M %p"; do sleep 60; done

    font pango: monospace 10

    # Basic Tokyo Night colors
    colors {
        statusline #c0caf5
        background #1a1b26
        focused_workspace  #1a1b26 #c0caf5 #1a1b26
        inactive_workspace #32323200 #32323200 #5c5c5c
    }
}

