# ==============================================================================
# Styles
# ==============================================================================

# Borders
default_border pixel 3
gaps inner 10
gaps outer 0

